### ISSUE TITLE
Improper chaos value in map list

### ISSUE THREAD

**Issue by Alexis-Grimm** [briansd9/exile-diary#42]
Hello, When i look in my recent maps list I will notice that a couple of my maps every once and a while will show much higher chaos values than I expected from them given what I noticed picking up. Naturally I click on these maps to see what I got that I hadn't noticed, however once within the details of the map, the item list and chaos value will demonstrate a much more accurate and believable number. here are a couple examples:
Temple Map: 56.63 Chaos when in reality I got 18.05
![image](https://user-images.githubusercontent.com/23371612/71639364-36ad9d00-2c43-11ea-81f7-c7194487e3be.png)
An even more extreme example this canyon map: 51.54 chaos when in reality I found 11.86
![image](https://user-images.githubusercontent.com/23371612/71639391-ceab8680-2c43-11ea-956a-c673aeb5d0f0.png)
These are rather extreme examples however I have noticed that almost all of my maps and zones have small inaccuracies in the same way, between 2 and 5 chaos usually sometimes higher sometimes lower. These i'm not so worried about it's just these 30-40 chaos inaccuracies that get me. It's not that the maps themselves are getting incorrect values as far as i can tell the value in the details is fairly accurate, it's specifically the value shown in the map list.

**Comment by Alexis-Grimm** [comment]
Along with this you will notice that in both of these maps it says that i picked up remnants of corruption, i did not pick up any remnants of corruption, these are the remnants of corruption that i keep in my inventory all the time and yet they (and multiple other currencies I carry around for strongboxes) show up as gains in nearly every map

**Comment by briansd9** [comment]
Hello, and thanks for the support!

Are you experiencing these problems consistently? Was only able to replicate the issue when the PoE servers were temporarily unable to retrieve my inventory... it seems that when this happens your entire inventory will be treated as "newly picked up" and added to the map value.

I've implemented a fix in v0.2.44, please check if the problem still persists.

**Comment by Alexis-Grimm** [comment]
Yeah i was experiencing both issues consistently, with the most recent update i'm not experiencing the second issue, however i'm still experiencing the first issue where a map on the list will show a different chaos value than the actual gained chaos value. So it would seem they aren't related.

**Comment by briansd9** [comment]
I see... the only legitimate reason I can see for the discrepancy is the `Ignore non-bulk items less than __ chaos in value` in the settings screen ("Stash" tab). Have you changed this setting?

Also, can you send me these files for debugging?

`%appdata%\exile-diary\log.txt`

`%appdata%\exile-diary\<CHARACTERNAME>.db` (if it's not too large)

**Comment by Alexis-Grimm** [comment]
Oh yeah that actually makes sense, i had it set to ignore non-bulk items below 1 chaos, which actually accounts for the discrepancies i am currently getting, I'll make sure to check it tomorrow to see if i still get them now that i have it set to 0, thanks!

**Comment by Alexis-Grimm** [comment]
[log.txt](https://github.com/briansd9/exile-diary/files/4033907/log.txt)

Can't seem to upload the .db file on git hub because of the file type.

**Comment by briansd9** [comment]
Hmm, it seems that the issue I mentioned (unable to get inventory) is happening fairly often for you, once every few hours but sometimes multiple times an hour. It's indicated by this line in the log file:

`Failed to get current inventory: Error: connect ETIMEDOUT 104.19.185.16:443`

The root cause is bad connection from the PoE servers to you, so I can't fix it directly... will think about how to handle this better. Would a popup message at the bottom warning about this be OK for you?

**Comment by Alexis-Grimm** [comment]
Uh no that's fine now that i know the problem, I've been meaning to improve my network, currently running on wifi, want to connect by Ethernet.

**Comment by RHBallistic** [comment]
I believe the net worth on the Main screen is still calculating the value of items hidden by the "ignore non-bulk items less than" setting, which is causing profit values to be different on the Main screen summary and the individual map details pane.
